version: '3.6'
services:
  telegraf:
    image: telegraf:1.19
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - ./telegraf/metrics:/tmp/metrics
    ports:
    - '57000:57000'